//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package Engine.Xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <attribute name="initial" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       <attribute name="d" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       <attribute name="allow-mint" use="required">
 *         <simpleType>
 *           <restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             <enumeration value="false"/>
 *             <enumeration value="true"/>
 *           </restriction>
 *         </simpleType>
 *       </attribute>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "GM-order-book")
public class GMOrderBook {

    @XmlAttribute(name = "initial", required = true)
    protected int initial;
    @XmlAttribute(name = "d", required = true)
    protected int d;
    @XmlAttribute(name = "allow-mint", required = true)
    protected String allowMint;

    /**
     * Gets the value of the initial property.
     * 
     */
    public int getInitial() {
        return initial;
    }

    /**
     * Sets the value of the initial property.
     * 
     */
    public void setInitial(int value) {
        this.initial = value;
    }

    /**
     * Gets the value of the d property.
     * 
     */
    public int getD() {
        return d;
    }

    /**
     * Sets the value of the d property.
     * 
     */
    public void setD(int value) {
        this.d = value;
    }

    /**
     * Gets the value of the allowMint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowMint() {
        return allowMint;
    }

    /**
     * Sets the value of the allowMint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowMint(String value) {
        this.allowMint = value;
    }

}
