//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package Engine.Xml;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element ref="{}initial-cash"/>
 *         <element ref="{}GM-market-maker" minOccurs="0"/>
 *       </sequence>
 *       <attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "initialCash",
    "gmMarketMaker"
})
@XmlRootElement(name = "GM-user")
public class GMUser {

    @XmlElement(name = "initial-cash")
    protected int initialCash;
    @XmlElement(name = "GM-market-maker")
    protected GMMarketMaker gmMarketMaker;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the initialCash property.
     * 
     */
    public int getInitialCash() {
        return initialCash;
    }

    /**
     * Sets the value of the initialCash property.
     * 
     */
    public void setInitialCash(int value) {
        this.initialCash = value;
    }

    /**
     * Gets the value of the gmMarketMaker property.
     * 
     * @return
     *     possible object is
     *     {@link GMMarketMaker }
     *     
     */
    public GMMarketMaker getGMMarketMaker() {
        return gmMarketMaker;
    }

    /**
     * Sets the value of the gmMarketMaker property.
     * 
     * @param value
     *     allowed object is
     *     {@link GMMarketMaker }
     *     
     */
    public void setGMMarketMaker(GMMarketMaker value) {
        this.gmMarketMaker = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
